Pdfid base switched to alpine

diff --git a/pdfid/Dockerfile b/pdfid/Dockerfile
--- a/pdfid/Dockerfile
+++ b/pdfid/Dockerfile
@@ -16,16 +16,23 @@
 # plugin_nameobfuscation.py
 # plugin_triage.py
 
-FROM alpine:latest
-RUN apk update && apk add \
-	python \
-	wget \
-	unzip \
-	git
+FROM alpine:3.9
 
-RUN wget didierstevens.com/files/software/pdfid_v0_2_5.zip \
-    && unzip pdfid_v0_2_5.zip -d /pdfid \
-    && rm *.zip
+LABEL MAINTAINER=cincan.io
+
+RUN apk update && apk add --no-cache \
+	python2=2.7.16-r1 \
+	wget=1.20.3-r0 \
+	unzip=6.0-r4 \
+        git=2.20.1-r0
+
+# Get pdfid, check integrity, unzip, clean up.
+RUN wget https://didierstevens.com/files/software/pdfid_v0_2_5.zip \
+	&& if [ ! "$(sha256sum pdfid_v0_2_5.zip |awk '{print toupper($1)}')" = \
+	"4DD43D7BDA885C5A579FC1F797E93A536E1DB5A4AB52A9337759A69D3B0250E0" ]; then \
+	echo "Integrity check failed"; exit 1; fi \
+	&& unzip pdfid_v0_2_5.zip -d /pdfid \
+	&& rm pdfid_v0_2_5.zip
 
 ENTRYPOINT ["/usr/bin/python", "pdfid/pdfid.py"]
-
+CMD ["--help"]
