pdfid updated with modified one, supporting JSON output

diff --git a/pdfid/Dockerfile b/pdfid/Dockerfile
--- a/pdfid/Dockerfile
+++ b/pdfid/Dockerfile
@@ -13,11 +13,18 @@ RUN apk update && apk add --no-cache \
 	git=2.20.1-r0
 
 # Get pdfid, check integrity, unzip, clean up.
+# Replace main script of pdfid with one supporting JSON output
 RUN wget https://didierstevens.com/files/software/pdfid_v0_2_5.zip \
 	&& if [ ! "$(sha256sum pdfid_v0_2_5.zip |awk '{print toupper($1)}')" = \
 	"4DD43D7BDA885C5A579FC1F797E93A536E1DB5A4AB52A9337759A69D3B0250E0" ]; then \
 	echo "Integrity check failed"; exit 1; fi \
 	&& unzip pdfid_v0_2_5.zip -d /pdfid \
-	&& rm pdfid_v0_2_5.zip
+	&& rm pdfid_v0_2_5.zip && \
+	rm pdfid/pdfid.py && \
+	wget https://raw.githubusercontent.com/Nicceboy/DidierStevensSuite/master/pdfid.py -P pdfid \
+	&& if [ ! "$(sha256sum pdfid/pdfid.py |awk '{print toupper($1)}')" = \
+	"EA7392B53186BEA4879085286144EF22CE0C1ECEBBEC81FE91FEB87526B66EA9" ]; then \
+	echo "Integrity check failed"; exit 1; fi
+
 ENTRYPOINT ["/usr/bin/python", "pdfid/pdfid.py"]
 CMD ["--help"]
